server:
 port: 4989
#mysql_setting
spring:
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/
   username: 
   password: 
#mybatis
mybatis:
  type-aliases-package: boot.sagu.*
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
jwt:
  secret: 'your-very-long-and-secure-secret-key-that-is-at-least-256-bits'
  expiration: 3600000