server:
  port: 4989
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://project4989.c5200is4auzz.ap-northeast-2.rds.amazonaws.com:3306/sagupalgu
    username: admin4989
    password: project49898949
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  # 정적 리소스 설정 추가
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, file:save/
  # 분리된 설정 파일들을 포함하도록 설정
  profiles:
    include: 
      - oauth
      - coolsms

#mybatis
mybatis:
  type-aliases-package: boot.sagu.dto
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

#jwt
jwt:
  secret: 'your-very-long-and-secure-secret-key-that-is-at-least-256-bits'
  expiration: 21600000
portone:
  api-key: YOUR_REST_API_KEY
  api-secret: YOUR_REST_API_SECRET
kakao:
  rest:
    api:
      key: 137f888033bc0c17b0f4945a9f901900