server:
  port: 4989

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://project4989.c5200is4auzz.ap-northeast-2.rds.amazonaws.com:3306/sagupalgu
    username: admin4989
    password: project49898949
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  #소셜 로그인 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '[구글 클라이언트 ID]'
            client-secret: '[구글 클라이언트 시크릿]'
            scope:
              - profile
              - email
          kakao:
            client-id: '[카카오 REST API 키]'
            client-secret: '[카카오 Client Secret]' # Client Secret을 발급받은 경우에만 입력
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" # Spring Boot 3부터는 registrationId를 사용
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#mybatis
mybatis:
  type-aliases-package: boot.sagu.dto
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

#jwt
jwt:
  secret: 'your-very-long-and-secure-secret-key-that-is-at-least-256-bits'
  expiration: 21600000

# CoolSMS
coolsms:
  api-key: 'NCSDJNFKIX6MFYPO'
  api-secret: '2A3QAHAVIG8UZREZ3OW0AN7S3I8AHS3A'
  sender-phone: '01095801813'